import type { Lang } from "./i18n";

export const experienceCopy: Record<Lang, Record<string, string>> = {
  es: {
    nav_collaborations: "Colaboraciones", collab_kicker: "Misión real / Experiencia profesional",
    collab_title_a: "Colaboraciones", collab_title_b: "con empresas.",
    collab_intro: "Del código a un sitio publicado: proyectos desarrollados para empresas reales, con necesidades y una identidad propias.",
    collab_badge: "Proyecto real · Sitio publicado", collab_sector: "Sector veterinario · Chile",
    collab_description: "Desarrollé el sitio web de Clínica Veterinaria Felycan: un proyecto real llevado a producción para una empresa del sector veterinario.",
    collab_role_label: "Mi participación", collab_role: "Programación y desarrollo del sitio web",
    collab_result_label: "Resultado", collab_result: "Sitio disponible en el dominio de la clínica",
    collab_permission: "Presentado en mi portafolio con autorización de Clínica Veterinaria Felycan.",
    collab_visit: "Visitar sitio web", collab_contact: "Hablemos de tu proyecto",
    collab_alt: "Captura del sitio de Clínica Veterinaria Felycan, desarrollado por Francisco Guzmán; muestra la portada y la presentación de la doctora Jessica Zavala.",
    collab_preview: "Vista previa del sitio publicado", collab_preview_note: "Si la conexión es rápida se intenta abrir una vista en vivo. Si el navegador no la permite o la conexión es lenta, se muestra la captura local optimizada.",
    theme_label: "Cambiar tema espacial", theme_heading: "Elige tu universo", theme_purple: "Morado", theme_green: "Verde", theme_red: "Rojo", theme_sky: "Celeste", theme_supernova: "Supernova", theme_supernova_detail: "Dorado / naranja eléctrico",
    notfound_title: "Página no encontrada · Francisco Guzmán", notfound_kicker: "Señal perdida / Error 404", notfound_heading: "Esta página se perdió", notfound_highlight: "en el espacio.", notfound_description: "Las coordenadas de este enlace no llevan a ninguna página. Vuelve al observatorio y continúa explorando mi universo digital.", notfound_home: "Volver al inicio", notfound_collab: "Ver colaboraciones",
  },
  en: {
    nav_collaborations: "Collaborations", collab_kicker: "Real mission / Professional experience",
    collab_title_a: "Collaborations", collab_title_b: "with businesses.",
    collab_intro: "From code to a published website: projects built for real businesses, with their own needs and identity.",
    collab_badge: "Real project · Published website", collab_sector: "Veterinary sector · Chile",
    collab_description: "I developed the website for Clínica Veterinaria Felycan: a real project brought to production for a veterinary business.",
    collab_role_label: "My contribution", collab_role: "Website programming and development",
    collab_result_label: "Outcome", collab_result: "Website available on the clinic’s domain",
    collab_permission: "Featured in my portfolio with permission from Clínica Veterinaria Felycan.",
    collab_visit: "Visit website", collab_contact: "Let’s talk about your project",
    collab_alt: "Screenshot of Clínica Veterinaria Felycan’s website, developed by Francisco Guzmán, showing the home page and Dr. Jessica Zavala’s introduction.",
    collab_preview: "Published website preview", collab_preview_note: "On fast connections the live website is attempted. If the browser blocks it or the connection is slow, the optimized local screenshot is shown.",
    theme_label: "Change space theme", theme_heading: "Choose your universe", theme_purple: "Purple", theme_green: "Green", theme_red: "Red", theme_sky: "Sky blue", theme_supernova: "Supernova", theme_supernova_detail: "Gold / electric orange",
    notfound_title: "Page not found · Francisco Guzmán", notfound_kicker: "Signal lost / Error 404", notfound_heading: "This page got lost", notfound_highlight: "in space.", notfound_description: "This link’s coordinates do not lead to a page. Return to the observatory and keep exploring my digital universe.", notfound_home: "Back to home", notfound_collab: "View collaborations",
  },
  pt: {
    nav_collaborations: "Colaborações", collab_kicker: "Missão real / Experiência profissional",
    collab_title_a: "Colaborações", collab_title_b: "com empresas.",
    collab_intro: "Do código a um site publicado: projetos desenvolvidos para empresas reais, com necessidades e identidade próprias.",
    collab_badge: "Projeto real · Site publicado", collab_sector: "Setor veterinário · Chile",
    collab_description: "Desenvolvi o site da Clínica Veterinaria Felycan: um projeto real levado à produção para uma empresa do setor veterinário.",
    collab_role_label: "Minha participação", collab_role: "Programação e desenvolvimento do site",
    collab_result_label: "Resultado", collab_result: "Site disponível no domínio da clínica",
    collab_permission: "Apresentado no meu portfólio com autorização da Clínica Veterinaria Felycan.",
    collab_visit: "Visitar site", collab_contact: "Vamos falar do seu projeto",
    collab_alt: "Captura do site da Clínica Veterinaria Felycan, desenvolvido por Francisco Guzmán, mostrando a página inicial e a apresentação da doutora Jessica Zavala.",
    collab_preview: "Prévia do site publicado", collab_preview_note: "Em conexões rápidas, tenta abrir o site ao vivo. Se o navegador bloquear ou a conexão estiver lenta, a captura local otimizada é exibida.",
    theme_label: "Mudar tema espacial", theme_heading: "Escolha seu universo", theme_purple: "Roxo", theme_green: "Verde", theme_red: "Vermelho", theme_sky: "Azul-celeste", theme_supernova: "Supernova", theme_supernova_detail: "Dourado / laranja elétrico",
    notfound_title: "Página não encontrada · Francisco Guzmán", notfound_kicker: "Sinal perdido / Erro 404", notfound_heading: "Esta página se perdeu", notfound_highlight: "no espaço.", notfound_description: "As coordenadas deste link não levam a nenhuma página. Volte ao observatório e continue explorando meu universo digital.", notfound_home: "Voltar ao início", notfound_collab: "Ver colaborações",
  },
  fr: {
    nav_collaborations: "Collaborations", collab_kicker: "Mission réelle / Expérience professionnelle",
    collab_title_a: "Collaborations", collab_title_b: "avec des entreprises.",
    collab_intro: "Du code à un site publié : des projets développés pour de vraies entreprises, avec leurs propres besoins et leur identité.",
    collab_badge: "Projet réel · Site publié", collab_sector: "Secteur vétérinaire · Chili",
    collab_description: "J’ai développé le site de Clínica Veterinaria Felycan : un projet réel mis en production pour une entreprise du secteur vétérinaire.",
    collab_role_label: "Ma contribution", collab_role: "Programmation et développement du site",
    collab_result_label: "Résultat", collab_result: "Site disponible sur le domaine de la clinique",
    collab_permission: "Présenté dans mon portfolio avec l’autorisation de Clínica Veterinaria Felycan.",
    collab_visit: "Visiter le site", collab_contact: "Parlons de votre projet",
    collab_alt: "Capture du site de Clínica Veterinaria Felycan, développé par Francisco Guzmán, montrant l’accueil et la présentation de la docteure Jessica Zavala.",
    collab_preview: "Aperçu du site publié", collab_preview_note: "Sur connexion rapide, le site en direct est tenté. Si le navigateur le bloque ou si la connexion est lente, la capture locale optimisée s’affiche.",
    theme_label: "Changer le thème spatial", theme_heading: "Choisissez votre univers", theme_purple: "Violet", theme_green: "Vert", theme_red: "Rouge", theme_sky: "Bleu ciel", theme_supernova: "Supernova", theme_supernova_detail: "Doré / orange électrique",
    notfound_title: "Page introuvable · Francisco Guzmán", notfound_kicker: "Signal perdu / Erreur 404", notfound_heading: "Cette page s’est perdue", notfound_highlight: "dans l’espace.", notfound_description: "Les coordonnées de ce lien ne mènent à aucune page. Revenez à l’observatoire et continuez à explorer mon univers digital.", notfound_home: "Retour à l’accueil", notfound_collab: "Voir les collaborations",
  },
};
