import { createContext, useContext } from "react";

export type Lang = "es" | "en" | "pt" | "fr";
export const defaultLang: Lang = "es";

export const languages: { code: Lang; label: string; short: string }[] = [
  { code: "es", label: "Español", short: "ES" },
  { code: "en", label: "English", short: "EN" },
  { code: "pt", label: "Português", short: "PT" },
  { code: "fr", label: "Français", short: "FR" },
];

const translations: Record<Lang, Record<string, string>> = {
  es: {
    skip: "Saltar al contenido", nav_home: "Inicio", nav_mobile: "Apps móviles", nav_windows: "Windows", nav_projects: "Constelaciones", nav_skills: "Habilidades", nav_contact: "Hablemos", nav_label: "Navegación principal", lang_label: "Idioma", menu_label: "Abrir o cerrar menú",
    hero_badge: "Órbita independiente / Chile", hero_intro: "Hola, soy Francisco Guzmán.", hero_title_a: "Explora mi", hero_title_b: "universo digital.", hero_desc: "Desarrollo apps Android nativas y experiencias web con una identidad visual propia: interfaces cuidadas, código sólido y proyectos pensados como sistemas vivos, no como plantillas genéricas.", hero_primary: "Iniciar recorrido", hero_secondary: "Abrir canal", hero_comment: "Cartografía de productos digitales", hero_ready: "Nueva señal detectada", hero_android_sub: "Kotlin + Compose", hero_web_sub: "Nebulosas web",     hero_scroll: "Bajar al mapa estelar", stat_mobile: "apps nativas", stat_desktop: "apps de escritorio", stat_web: "sistemas web", stat_total: "cuerpos celestes", art_bottom: "OBSERVATORIO DIGITAL · DISEÑO ORBITAL",
    mobile_kicker: "01 / Satélites nativos", mobile_title_a: "Apps que orbitan", mobile_title_b: "tu día a día.", mobile_desc: "Tres experiencias Android terminadas: productividad, gamificación y anti-desperdicio.", mobile_codepet_kind: "Aprendizaje × gamificación", mobile_at_kind: "Productividad × vida diaria", mobile_despensa_kind: "Anti-desperdicio × IA", mobile_codepet_alt: "Pantalla principal de CodePet", mobile_time_caption: "Un poco más de intención, cada día.", mobile_releases: "Ver versiones", mobile_ask: "Consultar por la app", mobile_privacy: "Privacidad",
    windows_kicker: "02 / Software Windows", windows_title_a: "Herramientas", windows_title_b: "de escritorio.", windows_desc: "Aplicaciones exclusivas para Windows con IA local, privacidad y flujos profesionales.", windows_status: "En proceso", windows_process_note: "Actualmente están en desarrollo activo; las capturas muestran el avance real de interfaz y flujo.",
    projects_kicker: "03 / Mapa de constelaciones", projects_title_a: "Sistemas", projects_title_b: "descubiertos.", projects_desc: "proyectos para explorar: plantillas web interactivas, productos de IA, booking, creatividad, apps nativas y software Windows dentro de una galaxia navegable.", filter_all: "Todos", filter_tech: "SaaS & IA", filter_booking: "Booking", filter_creative: "Creative", filter_mobile: "Apps Móviles", filter_desktop: "Software Windows", hud_open: "Abrir transmisión", hud_apk: "APK disponible", mobile_card_cta: "Conocer la app ↗", close: "Cerrar", preview_open_external: "Abrir ↗", preview_open_new_tab: "Abrir proyecto en nueva pestaña ↗", preview_iframe_error_title: "No se pudo embeber la vista previa", preview_iframe_error_desc: "Este sitio bloquea iframes. Ábrelo en una pestaña externa para verlo completo.", connection_slow_notice: "Vista previa optimizada", load_more: "Expandir galaxia", showing: "Mostrando", of: "de", projects: "proyectos", template_badge: "Plantilla demo", template_disclaimer: "Proyecto de portafolio — plantilla para demostrar habilidades de desarrollo y diseño",
    intent_kicker: "Exploración guiada", intent_label: "Orientar recorrido", intent_auto: "Mi recorrido", intent_auto_mobile: "Ordenado para una lectura cómoda desde móvil, sin ocultar el resto del portafolio.", intent_auto_desktop: "Ordenado para escritorio: primero sistemas amplios y software, sin ocultar las apps.", intent_mobile: "Android", intent_mobile_desc: "Prioriza apps nativas, capturas móviles y experiencias Kotlin.", intent_web: "Web", intent_web_desc: "Prioriza interfaces web, plantillas y sistemas navegables.", intent_ai: "IA", intent_ai_desc: "Prioriza proyectos donde la inteligencia artificial o automatización es parte del producto.", intent_desktop: "Windows", intent_desktop_desc: "Prioriza software de escritorio, privacidad local y flujos profesionales.", gallery_key_hint: "Usa ← → para cambiar captura.",
    skills_kicker: "03 / Estación técnica", skills_title_a: "El stack detrás", skills_title_b: "de cada misión.", skills_desc: "Herramientas para construir interfaces nativas, experiencias web adaptables y lógica backend confiable.", skill_android: "Experiencias nativas fluidas, modernas y listas para el ecosistema Android.", skill_frontend: "Del concepto visual a una interfaz responsive, clara y con personalidad.", skill_backend: "Estructura, datos y lógica para que la experiencia no sea solo fachada.",
    contact_kicker: "04 / Próxima misión", contact_title_a: "Tu próxima idea",     contact_title_b: "puede despegar.", contact_desc: "Una app, una web o una colaboración. Cuéntame qué tienes en mente y diseñemos una ruta para construirla.", contact_email_label: "Correo directo", contact_or_label: "También en:", footer_text: "Construyendo productos digitales con identidad propia", back_top: "Volver arriba",
  },
  en: {
    skip: "Skip to content", nav_home: "Home", nav_mobile: "Mobile apps", nav_windows: "Windows", nav_projects: "Constellations", nav_skills: "Skills", nav_contact: "Let's talk", nav_label: "Main navigation", lang_label: "Language", menu_label: "Toggle menu",
    hero_badge: "Independent orbit / Chile", hero_intro: "Hi, I'm Francisco Guzmán.", hero_title_a: "Explore my", hero_title_b: "digital universe.", hero_desc: "I build native Android apps and web experiences with a visual identity of their own: thoughtful interfaces, solid code and projects designed as living systems, not generic templates.", hero_primary: "Start the journey", hero_secondary: "Open channel", hero_comment: "Digital product cartography", hero_ready: "New signal detected", hero_android_sub: "Kotlin + Compose", hero_web_sub: "Web nebulas",     hero_scroll: "Scroll to the star map", stat_mobile: "native apps", stat_desktop: "desktop apps", stat_web: "web systems", stat_total: "celestial bodies", art_bottom: "DIGITAL OBSERVATORY · ORBITAL DESIGN",
    mobile_kicker: "01 / Native satellites", mobile_title_a: "Apps orbiting", mobile_title_b: "daily life.", mobile_desc: "Three finished Android experiences: productivity, gamification and anti-waste.", mobile_codepet_kind: "Learning × gamification", mobile_at_kind: "Productivity × daily life", mobile_despensa_kind: "Anti-waste × AI", mobile_codepet_alt: "CodePet home screen", mobile_time_caption: "A little more intention, every day.", mobile_releases: "View releases", mobile_ask: "Ask about the app", mobile_privacy: "Privacy",
    windows_kicker: "02 / Windows software", windows_title_a: "Desktop", windows_title_b: "tools.", windows_desc: "Windows-exclusive apps with local AI, privacy and professional workflows.", windows_status: "In progress", windows_process_note: "They are currently in active development; screenshots show real interface and workflow progress.",
    projects_kicker: "03 / Constellation map", projects_title_a: "Discovered", projects_title_b: "systems.", projects_desc: "projects to explore: interactive web templates, AI products, booking, creative work, native apps and Windows software inside a navigable galaxy.", filter_all: "All", filter_tech: "SaaS & AI", filter_booking: "Booking", filter_creative: "Creative", filter_mobile: "Mobile Apps", filter_desktop: "Windows Software", hud_open: "Open transmission", hud_apk: "APK available", mobile_card_cta: "Explore the app ↗", close: "Close", preview_open_external: "Open ↗", preview_open_new_tab: "Open project in new tab ↗", preview_iframe_error_title: "Preview unavailable", preview_iframe_error_desc: "This site blocks iframes. Open it in a new tab to view it fully.", connection_slow_notice: "Optimized preview", load_more: "Expand galaxy", showing: "Showing", of: "of", projects: "projects", template_badge: "Demo template", template_disclaimer: "Portfolio project — template to showcase development & design skills",
    intent_kicker: "Guided exploration", intent_label: "Guide the route", intent_auto: "My route", intent_auto_mobile: "Ordered for comfortable mobile reading, without hiding the rest of the portfolio.", intent_auto_desktop: "Ordered for desktop: larger systems and software first, without hiding the apps.", intent_mobile: "Android", intent_mobile_desc: "Prioritizes native apps, mobile screenshots and Kotlin experiences.", intent_web: "Web", intent_web_desc: "Prioritizes web interfaces, templates and navigable systems.", intent_ai: "AI", intent_ai_desc: "Prioritizes projects where AI or automation is part of the product.", intent_desktop: "Windows", intent_desktop_desc: "Prioritizes desktop software, local privacy and professional workflows.", gallery_key_hint: "Use ← → to change screenshot.",
    skills_kicker: "03 / Technical station", skills_title_a: "The stack behind", skills_title_b: "each mission.", skills_desc: "Tools for building native interfaces, responsive web experiences and reliable backend logic.", skill_android: "Fluid, modern native experiences ready for the Android ecosystem.", skill_frontend: "From visual concept to a responsive, clear interface with personality.", skill_backend: "Structure, data and logic so the experience is not only surface.",
    contact_kicker: "04 / Next mission", contact_title_a: "Your next idea",     contact_title_b: "can take off.", contact_desc: "An app, a website or a collaboration. Tell me what you have in mind and let's design a route to build it.", contact_email_label: "Direct email", contact_or_label: "Also at:", footer_text: "Building digital products with their own identity", back_top: "Back to top",
  },
  pt: {
    skip: "Ir para o conteúdo", nav_home: "Início", nav_mobile: "Apps móveis", nav_windows: "Windows", nav_projects: "Constelações", nav_skills: "Habilidades", nav_contact: "Vamos conversar", nav_label: "Navegação principal", lang_label: "Idioma", menu_label: "Abrir ou fechar menu",
    hero_badge: "Órbita independente / Chile", hero_intro: "Olá, sou Francisco Guzmán.", hero_title_a: "Explore meu", hero_title_b: "universo digital.", hero_desc: "Crio apps Android nativos e experiências web com identidade visual própria: interfaces cuidadas, código sólido e projetos pensados como sistemas vivos, não como modelos genéricos.", hero_primary: "Iniciar jornada", hero_secondary: "Abrir canal", hero_comment: "Cartografia de produtos digitais", hero_ready: "Novo sinal detectado", hero_android_sub: "Kotlin + Compose", hero_web_sub: "Nebulosas web",     hero_scroll: "Descer ao mapa estelar", stat_mobile: "apps nativos", stat_desktop: "apps de desktop", stat_web: "sistemas web", stat_total: "corpos celestes", art_bottom: "OBSERVATÓRIO DIGITAL · DESIGN ORBITAL",
    mobile_kicker: "01 / Satélites nativos", mobile_title_a: "Apps que orbitam", mobile_title_b: "o dia a dia.", mobile_desc: "Três experiências Android finalizadas: produtividade, gamificação e anti-desperdício.", mobile_codepet_kind: "Aprendizado × gamificação", mobile_at_kind: "Produtividade × vida diária", mobile_despensa_kind: "Anti-desperdício × IA", mobile_codepet_alt: "Tela inicial do CodePet", mobile_time_caption: "Um pouco mais de intenção, todos os dias.", mobile_releases: "Ver versões", mobile_ask: "Perguntar sobre o app", mobile_privacy: "Privacidade",
    windows_kicker: "02 / Software Windows", windows_title_a: "Ferramentas", windows_title_b: "de desktop.", windows_desc: "Apps exclusivos para Windows com IA local, privacidade e fluxos profissionais.", windows_status: "Em andamento", windows_process_note: "Atualmente estão em desenvolvimento ativo; as capturas mostram o avanço real da interface e do fluxo.",
    projects_kicker: "03 / Mapa de constelações", projects_title_a: "Sistemas", projects_title_b: "descobertos.", projects_desc: "projetos para explorar: templates web interativos, produtos de IA, booking, criatividade, apps nativos e software Windows dentro de uma galáxia navegável.", filter_all: "Todos", filter_tech: "SaaS & IA", filter_booking: "Booking", filter_creative: "Creative", filter_mobile: "Apps Móveis", filter_desktop: "Software Windows", hud_open: "Abrir transmissão", hud_apk: "APK disponível", mobile_card_cta: "Conhecer o app ↗", close: "Fechar", preview_open_external: "Abrir ↗", preview_open_new_tab: "Abrir projeto em nova aba ↗", preview_iframe_error_title: "A prévia não pôde ser incorporada", preview_iframe_error_desc: "Este site bloqueia iframes. Abra em uma nova aba para ver completo.", connection_slow_notice: "Prévia otimizada", load_more: "Expandir galáxia", showing: "Mostrando", of: "de", projects: "projetos", template_badge: "Template demo", template_disclaimer: "Projeto de portfólio — template para demonstrar habilidades de desenvolvimento e design",
    intent_kicker: "Exploração guiada", intent_label: "Orientar percurso", intent_auto: "Meu percurso", intent_auto_mobile: "Ordenado para leitura confortável no celular, sem ocultar o resto do portfólio.", intent_auto_desktop: "Ordenado para desktop: sistemas amplos e software primeiro, sem ocultar os apps.", intent_mobile: "Android", intent_mobile_desc: "Prioriza apps nativos, capturas móveis e experiências Kotlin.", intent_web: "Web", intent_web_desc: "Prioriza interfaces web, templates e sistemas navegáveis.", intent_ai: "IA", intent_ai_desc: "Prioriza projetos onde IA ou automação faz parte do produto.", intent_desktop: "Windows", intent_desktop_desc: "Prioriza software desktop, privacidade local e fluxos profissionais.", gallery_key_hint: "Use ← → para trocar a captura.",
    skills_kicker: "03 / Estação técnica", skills_title_a: "O stack por trás", skills_title_b: "de cada missão.", skills_desc: "Ferramentas para criar interfaces nativas, experiências web responsivas e lógica backend confiável.", skill_android: "Experiências nativas fluidas, modernas e prontas para o ecossistema Android.", skill_frontend: "Do conceito visual a uma interface responsiva, clara e com personalidade.", skill_backend: "Estrutura, dados e lógica para que a experiência não seja só aparência.",
    contact_kicker: "04 / Próxima missão", contact_title_a: "Sua próxima ideia",     contact_title_b: "pode decolar.", contact_desc: "Um app, um site ou uma colaboração. Conte o que você tem em mente e vamos desenhar uma rota para construir.", contact_email_label: "E-mail direto", contact_or_label: "Também em:", footer_text: "Construindo produtos digitais com identidade própria", back_top: "Voltar ao topo",
  },
  fr: {
    skip: "Aller au contenu", nav_home: "Accueil", nav_mobile: "Apps mobiles", nav_windows: "Windows", nav_projects: "Constellations", nav_skills: "Compétences", nav_contact: "Discutons", nav_label: "Navigation principale", lang_label: "Langue", menu_label: "Ouvrir ou fermer le menu",
    hero_badge: "Orbite indépendante / Chili", hero_intro: "Bonjour, je suis Francisco Guzmán.", hero_title_a: "Explorez mon", hero_title_b: "univers digital.", hero_desc: "Je crée des apps Android natives et des expériences web avec une identité visuelle propre : interfaces soignées, code solide et projets pensés comme des systèmes vivants, pas comme des modèles génériques.", hero_primary: "Commencer le voyage", hero_secondary: "Ouvrir le canal", hero_comment: "Cartographie de produits digitaux", hero_ready: "Nouveau signal détecté", hero_android_sub: "Kotlin + Compose", hero_web_sub: "Nébuleuses web",     hero_scroll: "Descendre vers la carte stellaire", stat_mobile: "apps natives", stat_desktop: "apps de bureau", stat_web: "systèmes web", stat_total: "corps célestes", art_bottom: "OBSERVATOIRE DIGITAL · DESIGN ORBITAL",
    mobile_kicker: "01 / Satellites natifs", mobile_title_a: "Des apps en orbite", mobile_title_b: "autour du quotidien.", mobile_desc: "Trois expériences Android terminées : productivité, gamification et anti-gaspillage.", mobile_codepet_kind: "Apprentissage × gamification", mobile_at_kind: "Productivité × vie quotidienne", mobile_despensa_kind: "Anti-gaspillage × IA", mobile_codepet_alt: "Écran d'accueil de CodePet", mobile_time_caption: "Un peu plus d'intention, chaque jour.", mobile_releases: "Voir les versions", mobile_ask: "Demander l'app", mobile_privacy: "Confidentialité",
    windows_kicker: "02 / Software Windows", windows_title_a: "Outils", windows_title_b: "de bureau.", windows_desc: "Applications exclusives Windows avec IA locale, confidentialité et flux professionnels.", windows_status: "En cours", windows_process_note: "Elles sont actuellement en développement actif ; les captures montrent l'avancement réel de l'interface et du flux.",
    projects_kicker: "03 / Carte des constellations", projects_title_a: "Systèmes", projects_title_b: "découverts.", projects_desc: "projets à explorer : templates web interactifs, produits IA, booking, création, apps natives et software Windows dans une galaxie navigable.", filter_all: "Tous", filter_tech: "SaaS & IA", filter_booking: "Booking", filter_creative: "Creative", filter_mobile: "Apps mobiles", filter_desktop: "Software Windows", hud_open: "Ouvrir la transmission", hud_apk: "APK disponible", mobile_card_cta: "Découvrir l'app ↗", close: "Fermer", preview_open_external: "Ouvrir ↗", preview_open_new_tab: "Ouvrir le projet dans un nouvel onglet ↗", preview_iframe_error_title: "Aperçu indisponible", preview_iframe_error_desc: "Ce site bloque les iframes. Ouvrez-le dans un nouvel onglet pour le voir entièrement.", connection_slow_notice: "Aperçu optimisé", load_more: "Étendre la galaxie", showing: "Affichage", of: "de", projects: "projets", template_badge: "Template démo", template_disclaimer: "Projet de portfolio — template pour montrer des compétences en développement et design",
    intent_kicker: "Exploration guidée", intent_label: "Orienter le parcours", intent_auto: "Mon parcours", intent_auto_mobile: "Ordonné pour une lecture confortable sur mobile, sans masquer le reste du portfolio.", intent_auto_desktop: "Ordonné pour desktop : systèmes larges et logiciels d'abord, sans masquer les apps.", intent_mobile: "Android", intent_mobile_desc: "Priorise les apps natives, captures mobiles et expériences Kotlin.", intent_web: "Web", intent_web_desc: "Priorise les interfaces web, templates et systèmes navigables.", intent_ai: "IA", intent_ai_desc: "Priorise les projets où l'IA ou l'automatisation fait partie du produit.", intent_desktop: "Windows", intent_desktop_desc: "Priorise les logiciels desktop, la confidentialité locale et les flux professionnels.", gallery_key_hint: "Utilisez ← → pour changer de capture.",
    skills_kicker: "03 / Station technique", skills_title_a: "Le stack derrière", skills_title_b: "chaque mission.", skills_desc: "Outils pour créer des interfaces natives, des expériences web responsives et une logique backend fiable.", skill_android: "Expériences natives fluides, modernes et prêtes pour l'écosystème Android.", skill_frontend: "Du concept visuel à une interface responsive, claire et pleine de personnalité.", skill_backend: "Structure, données et logique pour que l'expérience ne soit pas qu'une façade.",
    contact_kicker: "04 / Prochaine mission", contact_title_a: "Votre prochaine idée",     contact_title_b: "peut décoller.", contact_desc: "Une app, un site ou une collaboration. Dites-moi ce que vous avez en tête et dessinons une route pour le construire.", contact_email_label: "E-mail direct", contact_or_label: "Aussi sur :", footer_text: "Construire des produits digitaux avec leur propre identité", back_top: "Retour en haut",
  },
};

export function t(lang: Lang, key: string): string {
  return translations[lang]?.[key] ?? translations[defaultLang][key] ?? key;
}

export function getProjectI18n(project: { taglineES: string; taglineEN: string; taglinePT?: string; taglineFR?: string }, lang: Lang) {
  if (lang === "en") return project.taglineEN;
  if (lang === "pt") return project.taglinePT ?? project.taglineEN;
  if (lang === "fr") return project.taglineFR ?? project.taglineEN;
  return project.taglineES;
}

export const LangContext = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: defaultLang, setLang: () => {} });
export function useLang() { return useContext(LangContext); }
